main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#papers
    weight: 11
  - name: Presentations
    url: /#presentations
    weight: 12
  - name: Teaching
    url: /rl-course/
    weight: 13
  - name: News
    url: /#news
    weight: 14
