main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#papers
    weight: 11
  - name: Presentations
    url: /#presentations
    weight: 12
  - name: News
    url: /#news
    weight: 13
  - name: Pre College RL Course
    url: /rl-course/
    weight: 14
  - name: CV
    url: uploads/Yao_CV.pdf
    weight: 15
